server.port: 8090

spring.data.mongodb.uri: mongodb+srv://test:test@cluster0-kacdx.mongodb.net/test?retryWrites=true&w=majority

media-service:
  available-media:
    - titanic
    - avatar
    - interstellar
    - the martian
    - gatsby
    - gladiator
    - braveheart
    - inception
    - memento
    - two and a half men
    - star wars
    - the avengers
    - american sniper
    - john wick
    - the big bang theory
  check-frequency: 60000

omdb:
  apiKey: 69209ae6
  url: http://www.omdbapi.com